# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKclient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher'
  pod 'SwiftyJSON'	
  pod 'RealmSwift', '= 5.3.3'
  pod 'PromiseKit', '~> 6.13.1'
end
